language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"

before_install:
    - sudo apt-get -qq update
    - sudo mkdir -p /builds
    - sudo chmod a+rw /builds

install:
    - pip3 install tox -r requirements.txt

script:
    - tox -e lint
    - tox -e playback
